name: Build

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Destination platform'
        required: true
        default: all
        type: choice
        options:
          - all
          - unix
          - win
          # - macos
      branch:
        description: 'Specific Branch for building'
        required: true
        default: 'main'
      tag:
        description: 'Specific tag for building'
        required: false
        default: ''
        
jobs:

  build-unix:
    if: ${{ github.event.inputs.platform == 'all' || github.event.inputs.platform == 'unix' }}
    runs-on: ubuntu-latest
    steps:
      - uses: andyoknen/pocketnetcore-build-action@v1
        with:
          platform: 'unix'
          branch: ${{ github.event.inputs.branch }}
          tag: ${{ github.event.inputs.tag }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: unix
          path: ./out
          
  build-win:
    if: ${{ github.event.inputs.platform == 'all' || github.event.inputs.platform }} == 'win' }}
    runs-on: ubuntu-latest
    steps:
      - uses: andyoknen/pocketnetcore-build-action@v1
        with:
          platform: 'win'
          branch: ${{ github.event.inputs.branch }}
          tag: ${{ github.event.inputs.tag }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: win
          path: ./out
          
  build-macos:
    if: ${{ github.event.inputs.platform == 'implement' || github.event.inputs.platform == 'implement' }}
    runs-on: ubuntu-latest
    steps:
      - uses: andyoknen/pocketnetcore-build-action@v1
        with:
          platform: 'macos'
          branch: ${{ github.event.inputs.branch }}
          tag: ${{ github.event.inputs.tag }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos
          path: ./out
