name: make check

on:
  workflow_dispatch:
  pull_request:
    branches: [ $default-branch, 0.20, 0.21 ]
    types: [ready_for_review]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: apt update
      run: sudo apt-get update
    - name: install libdb
      run: |
        chmod 777 ./contrib/install_db4.sh 
        ./contrib/install_db4.sh `pwd`
    - name: install boost
      run: sudo apt-get install libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-test-dev libboost-thread-dev
    - name: Install dependencies
      run: sudo apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils python3 
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: |
        export BDB_PREFIX='/home/runner/work/pocketnet.core/pocketnet.core/db4'
        ./configure --enable-tests BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include"
    - name: make
      run: make -j2
    - name: make check
      run: make check
    - name: bench
      run: |
        cd src/bench
        ./bench_pocketcoin
        cd ../..
    - name: make deploy
      run: make deploy
    - uses: actions/upload-artifact@v2
      with:
        name: package
        path: pocketnet*.deb
